# Generated by Django 3.1.1 on 2021-01-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_text', models.CharField(max_length=200)),
                ('ques_image', models.ImageField(upload_to='ques_images/')),
                ('ans_text', models.CharField(max_length=500)),
                ('ans_audio', models.FileField(upload_to='ans_audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
